cc_library (
    name = "coroutine",

    srcs = glob(
        ["*.cc", "*.S"]
    ),

    hdrs = glob(
        ["*.h"]
    ),
    
    linkopts = ["-pthread"],

    visibility =  ["//visibility:public"],
)
