cc_test (
    name = "main",

    srcs = glob(
        ["*.cc"]
    ),
    deps = ["//coroutine:coroutine",
            "@gtest//:gtest_main"]
)

#copts = ["-I.", "-Iexternal/gtest/googletest/include"],
